[be] Add SimpleFakeQuantize for QAT
pytorch-labs/ao pull request #114
Opened 2024-04-02 22:51 UTC by andrewor14

Summary: This commit adds a simpler version of toq.FakeQuantize to be used for various flavors of QAT. In the future we should deprecate toq.FakeQuantize in favor of this new class.

Test Plan:
python test/quantization/test_qat_quant_api.py

Reviewers: jerryzh168

Subscribers: jerryzh168, supriyar

2024-04-03 15:26 UTC, jerryzh168 commented on torchao/quantization/_qat_quant_api.py
> +    @property
e.g. check how activation_post_process is accessed here: https://github.com/pytorch/pytorch/blob/main/torch/ao/quantization/fx/convert.py#L92

2024-04-03 16:47 UTC, jerryzh168 commented on torchao/quantization/_qat_quant_api.py
> +            return getattr(self.observer, name)
maybe just use if `hasattr(self,observer, name)` instead of hardcoding

2024-04-03 16:47 UTC, jerryzh168 commented on torchao/quantization/_qat_quant_api.py
> +        return self.observer.calculate_qparams()
we could potentially reroute function calls as well I think, maybe add a TODO here?

2024-04-03 16:58 UTC, cpuhrsch commented on torchao/quantization/_qat_quant_api.py
> +class SimpleFakeQuantize(FakeQuantizeBase):
Do we have docs on what an Observer and a fake quant op is?

2024-04-03 17:07 UTC, cpuhrsch requested changes
Let's spend some time chatting about the higher level design behind this. Do you have some docs I could read up on?

2024-04-04 14:29 UTC, andrewor14 commented
Closing after some offline discussions. We'll put all observation/fq logic in the linear module itself so we don't need another class.

2024-04-04 14:29 UTC, closed without merging